AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
Description: ""
Resources:
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "flashcards-cicd"
      Source: 
        BuildSpec: "buildspec-eks.yml"
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts: 
        EncryptionDisabled: false
        Name: "flashcards-cicd"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: 
        Type: "NO_CACHE"
      Environment: 
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild-flashcards-cicd-service-role"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig: 
        CloudWatchLogs: 
          Status: "ENABLED"
        S3Logs: 
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildProject2:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub "${CodeBuildProject3}-01"
      Source: 
        GitCloneDepth: 1
        GitSubmodulesConfig: 
          FetchSubmodules: false
        InsecureSsl: false
        Location: "https://github.com/alvv4240/FlashCards.git"
        ReportBuildStatus: false
        Type: "GITHUB"
      Artifacts: 
        EncryptionDisabled: false
        Location: "artifact-bucket-team1"
        Name: !Sub "${CodeBuildProject3}-01"
        NamespaceType: "NONE"
        OverrideArtifactName: false
        Packaging: "NONE"
        Path: "Build"
        Type: "S3"
      Cache: 
        Type: "NO_CACHE"
      Environment: 
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/FlashCards-SerRole"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig: 
        CloudWatchLogs: 
          Status: "ENABLED"
          GroupName: "FlashCards"
          StreamName: "FlashCards"
        S3Logs: 
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildProject3:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "FlashCards-CB"
      Description: "FlashCards CodeBuild"
      Source: 
        InsecureSsl: false
        Type: "CODEPIPELINE"
      Artifacts: 
        EncryptionDisabled: false
        Name: "FlashCards-CB"
        Packaging: "NONE"
        Type: "CODEPIPELINE"
      Cache: 
        Type: "NO_CACHE"
      Environment: 
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/FlashCards-SerRole"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig: 
        CloudWatchLogs: 
          Status: "ENABLED"
        S3Logs: 
          Status: "ENABLED"
          Location: "artifact-bucket-team1/Build-Artifacts"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

  CodeBuildProject4:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "flashcards-app"
      Description: "Flash Cards App"
      Source: 
        InsecureSsl: false
        Location: "prod-bucket-team1/FlashCards/"
        Type: "S3"
      Artifacts: 
        Type: "NO_ARTIFACTS"
      Cache: 
        Type: "NO_CACHE"
      Environment: 
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:6.0"
        ImagePullCredentialsType: "CODEBUILD"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      ServiceRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/codebuild-flashcard-ap-service-role"
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      EncryptionKey: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3"
      BadgeEnabled: false
      LogsConfig: 
        CloudWatchLogs: 
          Status: "ENABLED"
          GroupName: "/aws/codebuild/flashcards"
          StreamName: "flashcards"
        S3Logs: 
          Status: "DISABLED"
          EncryptionDisabled: false
      Visibility: "PRIVATE"

