AWSTemplateFormatVersion: 2010-09-09
Metadata:
  Generator: former2
  'AWS::CloudFormation::Designer':
    331063cb-c65a-4e8c-b126-6a002d767586:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    dd41ccbc-1a27-4c5e-8b2f-16820a68fc74:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
    1ceebaa3-7be5-4a93-a87f-48c77910a987:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 160
      z: 1
      embeds: []
    43b5d29d-cc7f-4b75-ae19-a07ffb95de4f:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 160
      z: 1
      embeds: []
Description: ''
Resources:
  CodePipelinePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: FlashCards-03Test
      RoleArn: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-${AWS::Region}-FlashCards-03
      ArtifactStore:
        Location: artifact-bucket-team1
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                BranchName: main
                ConnectionArn: !Sub >-
                  arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/e8076d68-d874-4c77-8fba-3dfff7d88a5f
                FullRepositoryId: alvv4240/FlashCards
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                BucketName: prod-bucket-team1
                Extract: 'true'
                ObjectKey: FlashCards
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: DeployVariables
              RunOrder: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 43b5d29d-cc7f-4b75-ae19-a07ffb95de4f
  CodePipelinePipeline2:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: flashcards-cicd-eksTest
      RoleArn: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-${AWS::Region}-flashcards-cicd-eks
      ArtifactStore:
        Location: !Sub 'codepipeline-${AWS::Region}-890199704765'
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                BranchName: main
                ConnectionArn: !Sub >-
                  arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/e8076d68-d874-4c77-8fba-3dfff7d88a5f
                FullRepositoryId: alvv4240/FlashCards
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                BucketName: artifact-bucket-team1
                Extract: 'false'
                ObjectKey: FlashCards/
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: BuildVariables
              RunOrder: 1
        - Name: BuildEks
          Actions:
            - Name: BuildEKS
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                EnvironmentVariables: !Sub >-
                  [{"name":"AWS_DEFAULT_REGION","value":"${AWS::Region}","type":"PLAINTEXT"},{"name":"AWS_CLUSTER_NAME","value":"cicd-flashcards","type":"PLAINTEXT"},{"name":"AWS_ACCOUNT_ID","value":"${AWS::AccountId}","type":"PLAINTEXT"},{"name":"IMAGE_REPO_NAME","value":"flashcards","type":"PLAINTEXT"},{"name":"IMAGE_TAG","value":"latest","type":"PLAINTEXT"}]
                ProjectName: flashcards-cicd
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              RunOrder: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1ceebaa3-7be5-4a93-a87f-48c77910a987
  CodePipelinePipeline3:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: FlashCards-deploymentTest
      RoleArn: !Sub >-
        arn:aws:iam::${AWS::AccountId}:role/service-role/AWSCodePipelineServiceRole-${AWS::Region}-FlashCards-deployment
      ArtifactStore:
        Location: !Sub 'codepipeline-${AWS::Region}-890199704765'
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                BranchName: main
                ConnectionArn: !Sub >-
                  arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/e8076d68-d874-4c77-8fba-3dfff7d88a5f
                FullRepositoryId: alvv4240/FlashCards
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                BucketName: codezipfilebucket
                Extract: 'false'
                ObjectKey: FlashCards
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: DeployVariables
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: lambda
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: '1'
              Configuration:
                FunctionName: lambda-s3-function
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              RunOrder: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: dd41ccbc-1a27-4c5e-8b2f-16820a68fc74
  CodePipelinePipeline4:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: IacTest
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/IaC'
      ArtifactStore:
        Location: artifact-bucket-team1
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                BranchName: main
                ConnectionArn: !Sub >-
                  arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/5dc4bebd-cbd2-42f4-b447-7aabcb658f47
                FullRepositoryId: alvv4240/project_IaC
                OutputArtifactFormat: CODE_ZIP
              OutputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: SourceVariables
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                BucketName: prod-bucket-team1
                Extract: 'true'
                ObjectKey: IaC
              InputArtifacts:
                - Name: SourceArtifact
              Region: !Ref 'AWS::Region'
              Namespace: DeployVariables
              RunOrder: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 331063cb-c65a-4e8c-b126-6a002d767586
